Update no post Educacao - kaggle
colaboradados/colaboradados.github.io pull request #1
Opened 2019-01-28 20:28 UTC by alefjan

add o site kaggle/datasets

2019-02-03 00:04 UTC, juditecypreste requested changes
Oi Alefjan!
Bem legal essa base! Obrigada por enviar!
Poderia colocá-la no formato html do página, para podermos aprovar? O modelo é o seguinte:
*****
<section>

<h2>Ancine</h2>
<ul>
<li><b><a href="https://www.ancine.gov.br/pt-br/acesso-a-informacao/dados_abertos">Dados Abertos</a></b>: https://www.ancine.gov.br/pt-br/acesso-a-informacao/dados_abertos</li>
</ul>

<h2>Recam</h2>
<ul>
<li><b><a href="http://www.recam.org/?do=db&set_lang=pt">Base de dados de Filmes do Mercosul</a></b>: http://www.recam.org/?do=db&set_lang=pt</li>
</ul>

<h2>MNEMOCINE</h2>
<ul>
<li><b><a href="http://silenciosos.l2o.com.br/cgi-bin/wxis.exe/iah/scripts/?IsisScript=iah.xis&lang=pt&base=VIDEO">Base de dados de filmes estrangeiros exibidos no país entre o Omniógrafo (1896) e a passagem ao sonoro (1934)</a></b>: http://silenciosos.l2o.com.br/cgi-bin/wxis.exe/iah/scripts/?IsisScript=iah.xis&lang=pt&base=VIDEO</li>
</ul>

</section>
*****
No caso, a nova base tem que ficar dentro do "section", e não em um "section" próprio como você nos enviou. Isso vai nos ajudar a deixar organizado o código. Poderia também diminuir a explicação? algo como 'Bases de dados para competições Data Science'? É para manter o padrão de frase curta.

Obrigada por colaborar, e aguardamos as modificações!

2019-02-05 02:13 UTC, anapauladsmendes commented
Oi @alefjan houveram conflitos com a master. Você poderia atualizar o seu repositório local e remoto e corrigir os conflitos? Vi que as bases que você inseriu também seguem a sintaxe html, poderia corrigi-las para a sintaxe markdown? Corrigimos a sintaxe do arquivo e será mais fácil para outras pessoas contribuirem. Muito obrigada pela sua contribuição! :smile:

2019-02-05 12:17 UTC, merged

2019-02-05 12:21 UTC, alefjan commented
Atualizado para markdown e add o kaggle com um titulo mais simplificado

2019-02-05 12:22 UTC, anapauladsmendes commented
Muito obrigada pela contribuição! :smile: