Added some cities from RN
colaboradados/colaboradados.github.io pull request #113
Opened 2019-10-04 18:14 UTC by kaardeco

# Description
- update category:city Natal
- added a new portal with open data from GOVE
- added new cities (Caraúbas, Mossoró and Apodi)
-- added transparency portals and open data from this cities

2019-10-05 21:25 UTC, atarrisse requested changes
Corrigir o título de um item e faltou uma besteirinha no último item, em Apodi.

2019-10-05 21:25 UTC, atarrisse commented on _states/rio-grande-do-norte.md
> + **[Dados Abertos do Município de Apodi](https://www.gove.digital/dados-abertos/#/apodi-rn/geral)**: https://www.gove.digital/dados-abertos/#/apodi-rn/geral
Faltou um traço neste último.

2019-10-05 21:31 UTC, atarrisse commented on _states/rio-grande-do-norte.md
>  -  **[Portal da Transparência e Mobilidade Urbana de Natal](http://dados.natal.br/)**: http://dados.natal.br/
Portal da Transparência **da** Mobilidade Urbana de Natal
<kbd><img width="883" alt="image" src="https://user-images.githubusercontent.com/4750042/66261118-40d41280-e79e-11e9-9ef5-3afe13128893.png"></kbd>

2019-10-06 00:57 UTC, kaardeco commented
Correções feitas!

2019-10-08 02:45 UTC, anapaulamendes commented
Olá, @kaardeco , existem muitos conflitos nesse PR após o merge de outros. Você pode corrigi-los?

2019-10-15 00:03 UTC, juditecypreste commented
@kaardeco parece que ainda há conflitos aqui. Poderia dar uma olhadinha?

2019-10-16 21:13 UTC, kaardeco commented
Estava em semana de prova, perdão a demora. Até a sexta eu faço resolvo tudo!

2019-10-19 15:04 UTC, anapaulamendes commented
@kaardeco você vai continuar esse PR?

2019-10-19 20:58 UTC, kaardeco commented
> @kaardeco você vai continuar esse PR?

Sim!!! Tenho umas coisas pra adicionar!

2019-10-24 05:03 UTC, kaardeco commented
Corrigido e adicionado!

2019-10-28 23:51 UTC, anapaulamendes commented
Obrigada, @kaardeco :heart:

2019-10-28 23:52 UTC, merged