add citys
colaboradados/colaboradados.github.io pull request #134
Opened 2019-10-08 19:57 UTC by alibabraga

### Título

### Este PR faz o seguinte:

- [ ] Inclui uma nova base de dados
- [ ] Inclui nova funcionalidade
- [ ] Altera o layout
- [x ] Formatação ou refactor de código
- [ ] Resolve a issue#{id}

---

### Se há mudança de layout ou funcionaliade, foi testado em quais browsers:

Mobile

- Android
  - [ ] Chrome
- iOS
  - [ ] Chrome
  - [ ] Safari

Desktop

- Windows
  - [ ] Chrome
  - [ ] Firefox
- MacOs
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
- Linux
  - [ ] Chrome
  - [ ] Firefox

---

# Descrição
Descrição detalhada do PR. Se for o caso, inserir prints, gifs ou referências para melhor esclarecer as modificações

2019-10-08 20:25 UTC, atarrisse commented
@alibabraga vc pode incluir uma descrição no PR, por favor?

2019-10-08 20:27 UTC, atarrisse requested changes
A listagem deve estar em ordem alfabética...

2019-10-10 20:13 UTC, anapaulamendes commented on _states/minas-gerais.md
> +
É necessário por em ordem alfabética. Você pode corrigir isso?

2019-10-19 15:04 UTC, anapaulamendes commented
@alibabraga você vai continuar esse PR?

2019-10-28 23:52 UTC, closed without merging