add cidades
colaboradados/colaboradados.github.io pull request #135
Opened 2019-10-08 20:24 UTC by rixgrady

### Título

### Este PR faz o seguinte:

- [ ] Inclui uma nova base de dados
- [ ] Inclui nova funcionalidade
- [ ] Altera o layout
- [ ] Formatação ou refactor de código
- [ ] Resolve a issue#{id}

---

### Se há mudança de layout ou funcionaliade, foi testado em quais browsers:

Mobile

- Android
  - [ ] Chrome
- iOS
  - [ ] Chrome
  - [ ] Safari

Desktop

- Windows
  - [ ] Chrome
  - [ ] Firefox
- MacOs
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
- Linux
  - [ ] Chrome
  - [ ] Firefox

---

# Descrição
Descrição detalhada do PR. Se for o caso, inserir prints, gifs ou referências para melhor esclarecer as modificações

2019-10-08 20:25 UTC, atarrisse commented
@rixgrady vc pode colocar uma descrição no PR, por favor?

2019-10-08 20:26 UTC, atarrisse requested changes
A listagem deve estar em ordem alfabética...

2019-10-10 20:12 UTC, anapaulamendes commented on _states/mato-grosso.md
> +### Sinop
É necessário por em ordem alfabética. Você pode corrigir?

2019-10-19 15:03 UTC, anapaulamendes commented
@rixgrady você vai continuar esse PR?

2019-10-19 15:07 UTC, rixgrady commented
Claro, se você puder me dar um tempo de uma semana eu vejo o que posso
fazer porquê mesmo sendo de lá ainda é muito difícil saber uma quantidade
grande de cidades então provável que só conhecerei umas 12 a 30 cidades

Em sáb, 19 de out de 2019 12:03, Ana Paula Mendes <notifications@github.com>
escreveu:

> @rixgrady <https://github.com/rixgrady> você vai continuar esse PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/colaboradados/colaboradados.github.io/pull/135?email_source=notifications&email_token=ANKN4BVBULMRY3MZACL6ZO3QPMOVLA5CNFSM4I6WWUVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBXSXDQ#issuecomment-544156558>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANKN4BUCI5IKEYGDW6HF5JTQPMOVLANCNFSM4I6WWUVA>
> .
>

2019-10-20 13:38 UTC, anapaulamendes commented
Certo, por favor, deixe em ordem alfabética. :smile:

2019-10-28 23:52 UTC, closed without merging