adicionei base de dados em Alagoas
colaboradados/colaboradados.github.io pull request #235
Opened 2020-10-03 18:40 UTC by MariaCarolinass

### Título

### Este PR faz o seguinte:

- [X] Inclui uma nova base de dados
- [ ] Inclui nova funcionalidade
- [ ] Altera o layout
- [ ] Formatação ou refactor de código
- [ ] Resolve a issue#{id}

---

### Se há mudança de layout ou funcionaliade, foi testado em quais browsers:

Mobile

- Android
  - [ ] Chrome
- iOS
  - [ ] Chrome
  - [ ] Safari

Desktop

- Windows
  - [ ] Chrome
  - [ ] Firefox
- MacOs
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
- Linux
  - [ ] Chrome
  - [ ] Firefox

---

# Descrição
Adicionei base de dados em Alagoas. Foram adicionados alguns municípios e links do Portal da Transparência da cidade e da câmara de vereadores

2020-10-04 21:25 UTC, atarrisse requested changes
Oi Carol, muito obrigada pela sua contribuição <3
Eu coloquei comentários em alguns links.
Se você tiver dúvidas, é só entrar em contato por aqui ou pelo grupo do telegram :)

2020-10-04 21:25 UTC, atarrisse commented on _states/alagoas.md
> +- **[Portal da Transparência da Câmara Municipal de Atalaia](http://www.atalaia.al.leg.br/)**: http://www.atalaia.al.leg.br/
Esse endereço é a home da Câmara Municipal. Você pode atualizar pro endereço do portal, por favor?

2020-10-04 21:25 UTC, atarrisse commented on _states/alagoas.md
> +- **[Portal da Transparência da Câmara Municipal de Batalha](http://www.batalha.al.leg.br/)**: http://www.batalha.al.leg.br/
Esse endereço é a home da Câmara Municipal. Você pode atualizar pro endereço do portal, por favor?

2020-10-04 21:25 UTC, atarrisse commented on _states/alagoas.md
> +- **[Portal da Transparência da Câmara Municipal de Belém](https://belem.al.gov.br/)**: https://belem.al.gov.br/
Esse site é da Prefeitura de Belém. O portal da transparência deles é o link que vc já colocou antes desse. Não precisamos desse segundo :)

2020-10-04 21:25 UTC, atarrisse commented on _states/alagoas.md
> +- **[Portal da Transparência do Município de Branquinha](http://5.172.159.218/branquinha/index.php?route=home&token=hdcw25a0km1s2wd3x1qq5x01a)**: http://5.172.159.218/branquinha/index.php?route=home&
Existe um link mais amigável pro Portal da Transparência de Branquinha: `http://www.iaplicativo.com/branquinha/`

2020-10-04 21:25 UTC, atarrisse commented on _states/alagoas.md
> +- **[Portal da Transparência da Câmara Municipal de Branquinha](http://branquinha.al.gov.br/home/)**: http://branquinha.al.gov.br/home/
Esse é o site da prefeitura de Branquinha. O portal da transparência deles é o link que vc já colocou antes desse. Não precisamos desse segundo :)

2020-10-04 21:25 UTC, atarrisse commented on _states/alagoas.md
> +- **[Portal da Transparência da Câmara Municipal de Cacimbinhas](http://www.cacimbinhas.al.leg.br/)**: http://www.cacimbinhas.al.leg.br/
Esse endereço é a home da Câmara Municipal. Você pode atualizar pro endereço do portal, por favor?

2020-10-04 21:25 UTC, atarrisse commented on _states/alagoas.md
> +- **[Portal da Transparência da Câmara Municipal de Cajueiro](https://www.cajueiro.al.leg.br/)**: https://www.cajueiro.al.leg.br/
Esse endereço é a home da Câmara Municipal. Você pode atualizar pro endereço do portal, por favor?

2020-10-05 13:44 UTC, MariaCarolinass commented
Acabei de atualizar as alterações em que pediu

2020-10-06 17:38 UTC, atarrisse approved these changes
Muito obrigada, Carol!
Feliz Hacktoberfest 🍺

2020-10-06 17:38 UTC, merged