Adiciona base de dados dos municípios do Ceará
colaboradados/colaboradados.github.io pull request #237
Opened 2020-10-03 19:53 UTC by igorjcl

### Título

### Este PR faz o seguinte:

- [x] Inclui uma nova base de dados
- [ ] Inclui nova funcionalidade
- [ ] Altera o layout
- [ ] Formatação ou refactor de código
- [ ] Resolve a issue#{id}

---

### Se há mudança de layout ou funcionaliade, foi testado em quais browsers:

Mobile

- Android
  - [ ] Chrome
- iOS
  - [ ] Chrome
  - [ ] Safari

Desktop

- Windows
  - [ ] Chrome
  - [ ] Firefox
- MacOs
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
- Linux
  - [x] Chrome
  - [ ] Firefox

---

# Descrição
Adiciona base de dados dos municípios do Ceará. Todos os municípios com a letra A.

2020-10-04 21:34 UTC, atarrisse requested changes
Oi Igor! Muito obrigada pela sua colaboração ⭐ 

Eu coloquei só um comentário pra mudar uma url. De resto tá tudo sussa!

2020-10-04 21:34 UTC, atarrisse commented on _states/ceara.md
> +- **[Portal da Transparência do Município de Alcântaras](http://www.portaldatransparencia.gov.br/localidades/2300507-alcantaras?ano=2020)**: http://www.portaldatransparencia.gov.br/localidades/230050
Você poderia retirar a query de ano da url, por favor?

2020-10-05 12:53 UTC, igorjcl commented on _states/ceara.md
> +- **[Portal da Transparência do Município de Alcântaras](http://www.portaldatransparencia.gov.br/localidades/2300507-alcantaras?ano=2020)**: http://www.portaldatransparencia.gov.br/localidades/230050
Olá, fiz a alteração

2020-10-11 19:04 UTC, atarrisse approved these changes
Feliz Hacktoberfest ⭐

2020-10-11 19:04 UTC, merged